# Instructions
         
For Part A, you need to scrape IMDB web page to find out top movies sorted by user votes. For each movie, you need to pull :
- movie_id
- rank
- title 
- runtime
- year
- rating
- votes

The URL of an page that include movies released between 2018 and 2020 sorted by number of votes is: 

https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc

Please click the URL and investigate how you can pull movie_id, rank, title,... from the webpage. 


**You need to write code after where I have <span style="color:red">'''  Your code here ...    '''.</span>**

***
Now let’s look at the read_m_from_html_string(url, num_of_m=50) function in detail. The parameter “num_of_m” in the function def read_m_from_html_string(url, num_of_m=50)
  represents the top number of movies you want to retrieve. For example, read_m_from_html_string(url,500) means that we want to extract top 500 movies released between, sorted by users' votes.

This function returns a list of dictionaries. Each dictionary represents one of the top movies, which could look like the following:

{
  
    'movie_id': 'tt7286456',
    'rank': '1.',
    'title': 'Joker',
    'runtime': 2h 2m,
    'year': '2019',
    'rating': '8.4',
    'votes': '1,421,777',
}


After you implement “read_m_from_html_string”, which will return a list of top movies, you need to export the movies list to a csv file.


***

After you done with scraping the needed data, you should clean and transform it as needed to make it ready for enriching the given "Movies.csv" dataset.
***

Finaly, export the enriched dataset to a CSV file:
Use the following naming convention: Project_3_PartA_Lastname.csv

In [3]:
import warnings
warnings.filterwarnings('ignore')
from bs4 import BeautifulSoup
import pandas as pd

***

## read_m_from_html_string

Inside this function, you need to write your code to pull the movies information from the provided Movies 500 HTML String text file.

For each movie, you need to pull :
- movie_id
- rank
- title 
- runtime
- year
- rating
- votes

To give examples on how to pull data from the web bage html string, I have included the code to pull the movie_id.
You need to inculde your code to pull the other needed movie information (title, rank, year, ......). You should have no missing values for each of the collected data.

The URL of an page that include movies released between 2018 and 2020 sorted by number of votes is: 

https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc

Please click the URL and investigate how you can pull movie_id, rank, title,... from the webpage using the Inspect option.

In [4]:
# This function, read a number of movies from a url html string. The default value is 50
def read_m_from_html_string(url, num_of_m=50):
    
    print(url)
    
    with open('TopVoted_500_Movies_HTML.txt', 'r', encoding="utf8") as file:
        html_string = file.read()   # to read the hmtl file as a string
        # I have included the Movies 500 HTML String.txt file in the project folder. Please take a look.
    
    # create a soup object
    soup = BeautifulSoup(html_string, "html.parser")
    
    '''
    Click the URL and investigate how you can pull movie_id, rank, title,... from the webpage.
    To investigate the html of a web page , For example:
    URL: https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc
    Right-click anywhere on the webpage, and at the very bottom of the menu that pops up, 
    you will see "Inspect", Click on it.
    '''
    '''
    Fetching a div that includes all the movies. This can be done by using find and find_all functions.
    for example, find_all('div') will give you all divs on the page. Actually, 
    this find or find_all function can have two parameters,
    in the code below 'div' is the tag name and 'ipc-page-grid__item ipc-page-grid__item--span-2' is an attribute 
    value of the tag. You can also do movie_list = soup.find('div', 'ipc-page-grid__item ipc-page-grid__item--span-2'). 
    Here you explicitly say: I want to find a div with 
    attribute class = 'ipc-page-grid__item ipc-page-grid__item--span-2'.
    
    Since on each imdb page, there's only one div with class = 'lister-list', we can use find rather than find_all. 
    Find_all will return a list of div tags, while find() will return only one div.
   '''     
    movie_list = soup.find('div', 'ipc-page-grid__item ipc-page-grid__item--span-2') 
    # this div contains all the listed movies in the requested html web page string.
    
    list_movies = [] # initialize the function return value, which is a list of movies. 
                     # This list will contains the scraped data transformed to a structured format.
    
    # Using count track the number of movies processed. now it's 0 - No movie has been processed yet.
    count = 0
    
    # each movie listed in a div with attribute value 'ipc-metadata-list-summary-item'.
    divs=  movie_list.find_all('li','ipc-metadata-list-summary-item') # To find all the listed movies in the page.
    for d in divs:
        dict_each_movie = {}  # initialize the movie dictionary to store the movie information.

        # Pulling the movie_id
        try:
            movie_id= d.find('a', 'ipc-title-link-wrapper').attrs['href']
            movie_id= movie_id[7:16]
            
        except:
            movie_id=""
        finally:
            dict_each_movie["movie_id"] = movie_id
            print(movie_id)
            
        # Pulling the rank
        try:
            rank_title = d.find('h3', 'ipc-title__text').text
            rank = rank_title.split('.')[0]
        except:
            rank = ""
        finally:
            dict_each_movie["rank"] = rank
            print(rank)        

        # Pulling the title
        try:
            title_full = d.find('h3', 'ipc-title__text').text
            title = title_full.split('. ', 1)[1]
        except:
            title = ""
        finally:
            dict_each_movie["title"] = title
            print(title)

        # Pulling the runtime
        try:
            metadata = d.find('div', 'sc-caa65599-6')
            spans = metadata.find_all('span', 'sc-caa65599-7')
            runtime = spans[1].text if len(spans) > 1 else ""
        except:
            runtime = ""
        finally:
            dict_each_movie["runtime"] = runtime
            print(runtime)
        
        # Pulling the year
        try:
            metadata = d.find('div', 'sc-caa65599-6')
            spans = metadata.find_all('span', 'sc-caa65599-7')
            year = spans[0].text if len(spans) > 0 else ""
        except:
            year = ""
        finally:
            dict_each_movie["year"] = year
            print(year)

        # Pulling the rating
          # the rating out of 10
        try:
            rating = d.find('span', 'ipc-rating-star--rating').text
        except:
            rating = ""
        finally:
            dict_each_movie["rating"] = rating
            print(rating)  

        # Pulling the votes
        try:
            votes = d.find('span', 'ipc-rating-star--voteCount').text
            votes = votes.strip('()')
        except:
            votes = ""
        finally:
            dict_each_movie["votes"] = votes
            print(votes)
        
        list_movies.append(dict_each_movie)  # To add the movie information to the movies list.

        count +=1
        print('===============================')
        print()
        if count == num_of_m:
            break # to exit from the loop.

    return list_movies

###  Call statement to scrap the TopVoted 500 movies
##### read_m_from_html_string(url,500)

In [5]:
url = "https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc"

Movies_list = read_m_from_html_string(url,500)  #to read the topVoted 500 movies
Movies_list

https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2020-12-31&sort=num_votes,desc
tt7286456
1
Joker
2h 2m
2019
8.3
 (1.7M
===============================

tt4154796
2
Avengers: Endgame
3h 1m
2019
8.4
 (1.4M
===============================

tt4154756
3
Avengers: Infinity War
2h 29m
2018
8.4
 (1.3M
===============================

tt6751668
4
Parasite
2h 12m
2019
8.5
 (1.1M
===============================

tt7131622
5
Once Upon a Time... in Hollywood
2h 41m
2019
7.6
 (936K
===============================

tt1825683
6
Black Panther
2h 14m
2018
7.3
 (893K
===============================

tt8946378
7
Knives Out
2h 10m
2019
7.9
 (837K
===============================

tt4633694
8
Spider-Man: Into the Spider-Verse
1h 57m
2018
8.4
 (758K
===============================

tt8579674
9
1917
1h 59m
2019
8.2
 (749K
===============================

tt5463162
10
Deadpool 2
1h 59m
2018
7.6
 (729K
===============================

tt6966692
11
Green Book
2h 10m
2018
8.2
 (661K
===============================

tt6723592
12
Tenet
2h 30m
2020
7.3
 (648K
===============================

tt4154664
13
Captain Marvel
2h 3m
2019
6.7
 (646K
===============================

tt6644200
14
A Quiet Place
1h 30m
2018
7.5
 (644K
===============================

tt1727824
15
Bohemian Rhapsody
2h 14m
2018
7.9
 (633K
===============================

tt6320628
16
Spider-Man: Far from Home
2h 9m
2019
7.3
 (618K
===============================

tt1270797
17
Venom
1h 52m
2018
6.6
 (593K
===============================

tt1950186
18
Ford v Ferrari
2h 32m
2019
8.1
 (548K
===============================

tt1477834
19
Aquaman
2h 23m
2018
6.8
 (546K
===============================

tt2527338
20
Star Wars: Episode IX - The Rise of Skywalker
2h 21m
2019
6.4
 (530K
===============================

tt1677720
21
Ready Player One
2h 20m
2018
7.4
 (530K
===============================

tt5095030
22
Ant-Man and the Wasp
1h 58m
2018
7.0
 (484K
===============================

tt2584384
23
Jojo Rabbit
1h 48m
2019
7.9
 (478K
===============================

tt6146586
24
John Wick: Chapter 3 - Parabellum
2h 10m
2019
7.4
 (468K
===============================

tt8772262
25
Midsommar
2h 28m
2019
7.1
 (468K
===============================

tt1302006
26
The Irishman
3h 29m
2019
7.8
 (462K
===============================

tt8367814
27
The Gentlemen
1h 53m
2019
7.8
 (445K
===============================

tt1517451
28
A Star Is Born
2h 16m
2018
7.6
 (442K
===============================

tt7784604
29
Hereditary
2h 7m
2018
7.3
 (440K
===============================

tt2948372
30
Soul
1h 40m
2020
8.0
 (419K
===============================

tt2737304
31
Bird Box
2h 4m
2018
6.6
 (414K
===============================

tt4912910
32
Mission: Impossible - Fallout
2h 27m
2018
7.7
 (412K
===============================

tt0448115
33
Shazam!
2h 12m
2019
7.0
 (408K
===============================

tt3778644
34
Solo: A Star Wars Story
2h 15m
2018
6.9
 (402K
===============================

tt2798920
35
Annihilation
1h 55m
2018
6.8
 (387K
===============================

tt6857112
36
Us
1h 56m
2019
6.8
 (381K
===============================

tt4881806
37
Jurassic World: Fallen Kingdom
2h 8m
2018
6.1
 (373K
===============================

tt7653254
38
Marriage Story
2h 17m
2019
7.9
 (366K
===============================

tt3606756
39
Incredibles 2
1h 58m
2018
7.5
 (361K
===============================

tt5727208
40
Uncut Gems
2h 15m
2019
7.4
 (343K
===============================

tt7349950
41
It: Chapter Two
2h 49m
2019
6.5
 (338K
===============================

tt9243946
42
El Camino
2h 2m
2019
7.3
 (328K
===============================

tt4123430
43
Fantastic Beasts: The Crimes of Grindelwald
2h 14m
2018
6.5
 (326K
===============================

tt0437086
44
Alita: Battle Angel
2h 2m
2019
7.3
 (318K
===============================

tt8228288
45
The Platform
1h 34m
2019
7.0
 (316K
===============================

tt8332922
46
A Quiet Place Part II
1h 37m
2020
7.2
 (314K
===============================

tt7975244
47
Jumanji: The Next Level
2h 3m
2019
6.6
 (311K
===============================

tt6139732
48
Aladdin
2h 8m
2019
6.9
 (309K
===============================

tt7349662
49
BlacKkKlansman
2h 15m
2018
7.5
 (308K
===============================

tt7126948
50
Wonder Woman 1984
2h 31m
2020
5.3
 (307K
===============================

tt1979376
51
Toy Story 4
1h 40m
2019
7.6
 (305K
===============================

tt6823368
52
Glass
2h 9m
2019
6.6
 (299K
===============================

tt7984734
53
The Lighthouse
1h 49m
2019
7.4
 (293K
===============================

tt6105098
54
The Lion King
1h 58m
2019
6.8
 (287K
===============================

tt8936646
55
Extraction
1h 56m
2020
6.8
 (284K
===============================

tt7713068
56
Birds of Prey and the Fantabulous Emancipation of One Harley Quinn
1h 49m
2020
6.1
 (279K
===============================

tt1051906
57
The Invisible Man
2h 4m
2020
7.1
 (278K
===============================

tt3281548
58
Little Women
2h 15m
2019
7.8
 (276K
===============================

tt2935510
59
Ad Astra
2h 3m
2019
6.5
 (275K
===============================

tt2704998
60
Game Night
1h 40m
2018
6.9
 (271K
===============================

tt5164214
61
Ocean's Eight
1h 50m
2018
6.3
 (257K
===============================

tt5083738
62
The Favourite
1h 59m
2018
7.5
 (253K
===============================

tt6806448
63
Fast & Furious Presents: Hobbs & Shaw
2h 17m
2019
6.4
 (252K
===============================

tt7846844
64
Enola Holmes
2h 3m
2020
6.6
 (239K
===============================

tt5606664
65
Doctor Sleep
2h 32m
2019
7.3
 (238K
===============================

tt1365519
66
Tomb Raider
1h 59m
2018
6.3
 (238K
===============================

tt9620292
67
Promising Young Woman
1h 53m
2020
7.5
 (231K
===============================

tt6499752
68
Upgrade
1h 40m
2018
7.5
 (229K
===============================

tt7798634
69
Ready or Not
1h 35m
2019
6.8
 (225K
===============================

tt3741700
70
Godzilla: King of the Monsters
2h 12m
2019
6.0
 (224K
===============================

tt4779682
71
The Meg
1h 53m
2018
5.7
 (224K
===============================

tt6565702
72
X-Men: Dark Phoenix
1h 53m
2019
5.7
 (223K
===============================

tt3766354
73
The Equalizer 2
2h 1m
2018
6.7
 (223K
===============================

tt4729430
74
Klaus
1h 36m
2019
8.2
 (222K
===============================

tt1027238
75
The Father
1h 37m
2020
8.2
 (221K
===============================

tt1560220
76
Zombieland: Double Tap
1h 39m
2019
6.7
 (220K
===============================

tt1028856
77
Another Round
1h 57m
2020
7.7
 (220K
===============================

tt2873282
78
Red Sparrow
2h 20m
2018
6.6
 (215K
===============================

tt1213641
79
First Man
2h 21m
2018
7.3
 (213K
===============================

tt4520988
80
Frozen II
1h 43m
2019
6.8
 (213K
===============================

tt6450804
81
Terminator: Dark Fate
2h 8m
2019
6.2
 (208K
===============================

tt8106534
82
6 Underground
2h 8m
2019
6.1
 (208K
===============================

tt9484998
83
Palm Springs
1h 30m
2020
7.4
 (207K
===============================

tt7556122
84
The Old Guard
2h 5m
2020
6.7
 (207K
===============================

tt2066051
85
Rocketman
2h 1m
2019
7.3
 (206K
===============================

tt5104604
86
Isle of Dogs
1h 41m
2018
7.8
 (206K
===============================

tt3104988
87
Crazy Rich Asians
2h
2018
6.9
 (205K
===============================

tt4701182
88
Bumblebee
1h 54m
2018
6.7
 (204K
===============================

tt1070874
89
The Trial of the Chicago 7
2h 9m
2020
7.7
 (203K
===============================

tt5848272
90
Ralph Breaks the Internet
1h 52m
2018
7.0
 (200K
===============================

tt2231461
91
Rampage
1h 47m
2018
6.1
 (198K
===============================

tt9770150
92
Nomadland
1h 47m
2020
7.3
 (197K
===============================

tt1502397
93
Bad Boys for Life
2h 4m
2020
6.5
 (194K
===============================

tt5884052
94
Pokémon: Detective Pikachu
1h 44m
2019
6.5
 (194K
===============================

tt5814060
95
The Nun
1h 36m
2018
5.4
 (191K
===============================

tt7668870
96
Searching
1h 42m
2018
7.6
 (190K
===============================

tt7040874
97
A Simple Favor
1h 57m
2018
6.7
 (188K
===============================

tt3794354
98
Sonic the Hedgehog
1h 39m
2020
6.5
 (187K
===============================

tt1618434
99
Murder Mystery
1h 37m
2019
6.1
 (185K
===============================

tt5052474
100
Sicario: Day of the Soldado
2h 2m
2018
7.1
 (185K
===============================

tt4500922
101
Maze Runner: The Death Cure
2h 23m
2018
6.3
 (184K
===============================

tt1502407
102
Halloween
1h 46m
2018
6.5
 (184K
===============================

tt7146812
103
Onward
1h 42m
2020
7.4
 (183K
===============================

tt8079248
104
Yesterday
1h 56m
2019
6.8
 (181K
===============================

tt6412452
105
The Ballad of Buster Scruggs
2h 13m
2018
7.2
 (180K
===============================

tt6155172
106
Roma
2h 15m
2018
7.6
 (176K
===============================

tt6628394
107
Bad Times at the El Royale
2h 21m
2018
7.1
 (176K
===============================

tt2386490
108
How to Train Your Dragon: The Hidden World
1h 44m
2019
7.4
 (173K
===============================

tt6266538
109
Vice
2h 12m
2018
7.2
 (172K
===============================

tt7984766
110
The King
2h 20m
2019
7.3
 (171K
===============================

tt6343314
111
Creed II
2h 10m
2018
7.1
 (167K
===============================

tt4566758
112
Mulan
1h 55m
2020
5.8
 (166K
===============================

tt7959026
113
The Mule
1h 56m
2018
7.0
 (166K
===============================

tt7395114
114
The Devil All the Time
2h 18m
2020
7.1
 (165K
===============================

tt5363618
115
Sound of Metal
2h
2019
7.7
 (164K
===============================

tt1314396
116
Borat Subsequent Moviefilm
1h 35m
2020
6.6
 (162K
===============================

tt2854926
117
Tag
1h 40m
2018
6.5
 (159K
===============================

tt3829266
118
The Predator
1h 47m
2018
5.3
 (158K
===============================

tt1488606
119
Triple Frontier
2h 5m
2019
6.5
 (158K
===============================

tt2283336
120
Men in Black: International
1h 54m
2019
5.6
 (158K
===============================

tt2222042
121
Love and Monsters
1h 49m
2020
6.9
 (156K
===============================

tt9893250
122
I Care a Lot
1h 58m
2020
6.4
 (156K
===============================

tt5886046
123
Escape Room
1h 39m
2019
6.4
 (156K
===============================

tt7737786
124
Greenland
1h 59m
2020
6.4
 (151K
===============================

tt1571234
125
Mortal Engines
2h 8m
2018
6.1
 (151K
===============================

tt1259528
126
Den of Thieves
2h 20m
2018
7.0
 (150K
===============================

tt8244784
127
The Hunt
1h 30m
2020
6.6
 (149K
===============================

tt8404614
128
The Two Popes
2h 5m
2019
7.6
 (144K
===============================

tt5758778
129
Skyscraper
1h 42m
2018
5.8
 (143K
===============================

tt9495224
130
Black Mirror: Bandersnatch
1h 30m
2018
7.1
 (142K
===============================

tt1489887
131
Booksmart
1h 42m
2019
7.1
 (138K
===============================

tt8110330
132
Dil Bechara
1h 41m
2020
8.3
 (137K
===============================

tt3846674
133
To All the Boys I've Loved Before
1h 39m
2018
7.0
 (136K
===============================

tt2557478
134
Pacific Rim: Uprising
1h 51m
2018
5.6
 (135K
===============================

tt8503618
135
Hamilton
2h 40m
2020
8.3
 (134K
===============================

tt6394270
136
Bombshell
1h 49m
2019
6.8
 (134K
===============================

tt7401588
137
Instant Family
1h 58m
2018
7.3
 (133K
===============================

tt5164432
138
Love, Simon
1h 50m
2018
7.5
 (132K
===============================

tt1590193
139
The Commuter
1h 44m
2018
6.3
 (132K
===============================

tt1018951
140
Soorarai Pottru
2h 33m
2020
8.6
 (130K
===============================

tt4777008
141
Maleficent: Mistress of Evil
1h 59m
2019
6.6
 (129K
===============================

tt1025100
142
Gemini Man
1h 57m
2019
5.7
 (129K
===============================

tt6048922
143
Greyhound
1h 31m
2020
7.0
 (128K
===============================

tt2139881
144
Long Shot
2h 5m
2019
6.8
 (127K
===============================

tt8613070
145
Portrait of a Lady on Fire
2h 2m
2019
8.0
 (123K
===============================

tt1226837
146
Beautiful Boy
2h
2018
7.4
 (121K
===============================

tt8267604
147
Capernaum
2h 6m
2018
8.4
 (120K
===============================

tt6189022
148
Angel Has Fallen
2h 1m
2019
6.4
 (120K
===============================

tt2548396
149
The Cloverfield Paradox
1h 42m
2018
5.5
 (119K
===============================

tt9071322
150
Dark Waters
2h 6m
2019
7.6
 (119K
===============================

tt6911608
151
Mamma Mia! Here We Go Again
1h 54m
2018
6.6
 (118K
===============================

tt1206885
152
Rambo: Last Blood
1h 29m
2019
6.1
 (117K
===============================

tt7752126
153
Brightburn
1h 30m
2019
6.1
 (117K
===============================

tt4364194
154
The Peanut Butter Falcon
1h 37m
2019
7.6
 (117K
===============================

tt4530422
155
Overlord
1h 50m
2018
6.6
 (114K
===============================

tt8108198
156
Andhadhun
2h 19m
2018
8.2
 (112K
===============================

tt5503686
157
Hustlers
1h 50m
2019
6.3
 (112K
===============================

tt1860242
158
The Highwaymen
2h 12m
2019
6.9
 (112K
===============================

tt2481498
159
Extremely Wicked, Shockingly Evil and Vile
1h 50m
2019
6.7
 (111K
===============================

tt8633478
160
Run
1h 30m
2020
6.7
 (109K
===============================

tt4332232
161
Fractured
1h 39m
2019
6.5
 (108K
===============================

tt7838252
162
K.G.F: Chapter 1
2h 34m
2018
8.2
 (108K
===============================

tt4218572
163
Widows
2h 9m
2018
6.8
 (108K
===============================

tt8580274
164
Eurovision Song Contest: The Story of Fire Saga
2h 3m
2020
6.5
 (108K
===============================

tt7939766
165
I'm Thinking of Ending Things
2h 14m
2020
6.5
 (107K
===============================

tt1088616
166
365 Days
1h 54m
2020
3.3
 (106K
===============================

tt1063345
167
Minari
1h 55m
2020
7.4
 (106K
===============================

tt2274648
168
Hellboy
2h
2019
5.3
 (106K
===============================

tt5774060
169
Underwater
1h 35m
2020
5.9
 (106K
===============================

tt2709692
170
The Grinch
1h 25m
2018
6.4
 (106K
===============================

tt7456310
171
Anna
1h 58m
2019
6.7
 (105K
===============================

tt4139588
172
Polar
1h 58m
2019
6.3
 (105K
===============================

tt3513548
173
Richard Jewell
2h 11m
2019
7.5
 (105K
===============================

tt8629748
174
Spenser Confidential
1h 51m
2020
6.2
 (105K
===============================

tt6292852
175
I Am Mother
1h 53m
2019
6.7
 (105K
===============================

tt0837563
176
Pet Sematary
1h 40m
2019
5.7
 (103K
===============================

tt4003440
177
The House That Jack Built
2h 32m
2018
6.8
 (103K
===============================

tt6924650
178
Midway
2h 18m
2019
6.7
 (103K
===============================

tt1034415
179
Suspiria
2h 32m
2018
6.7
 (103K
===============================

tt7550000
180
Project Power
1h 53m
2020
6.0
 (102K
===============================

tt3799232
181
The Kissing Booth
1h 45m
2018
5.9
 (101K
===============================

tt8364368
182
Crawl
1h 27m
2019
6.1
 (101K
===============================

tt8695030
183
The Dead Don't Die
1h 44m
2019
5.4
 (100K
===============================

tt6878306
184
News of the World
1h 58m
2020
6.8
 (100K
===============================

tt5028340
185
Mary Poppins Returns
2h 10m
2018
6.7
 (99K
===============================

tt4682266
186
The New Mutants
1h 34m
2020
5.3
 (99K
===============================

tt1413492
187
12 Strong
2h 10m
2018
6.5
 (99K
===============================

tt8623904
188
Last Christmas
1h 43m
2019
6.5
 (99K
===============================

tt8350360
189
Annabelle Comes Home
1h 46m
2019
5.9
 (99K
===============================

tt6998518
190
Mandy
2h 1m
2018
6.5
 (97K
===============================

tt7886848
191
Sadak 2
2h 13m
2020
1.2
 (97K
===============================

tt5220122
192
Hotel Transylvania 3: Summer Vacation
1h 37m
2018
6.3
 (96K
===============================

tt1103237
193
Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train
1h 57m
2020
8.2
 (94K
===============================

tt6472976
194
Five Feet Apart
1h 56m
2019
7.2
 (94K
===============================

tt8155288
195
Happy Death Day 2U
1h 40m
2019
6.2
 (94K
===============================

tt8075192
196
Shoplifters
2h 1m
2018
7.9
 (93K
===============================

tt1146482
197
The Social Dilemma
1h 34m
2020
7.6
 (93K
===============================

tt5688932
198
Sorry to Bother You
1h 52m
2018
6.9
 (93K
===============================

tt3224458
199
A Beautiful Day in the Neighborhood
1h 49m
2019
7.2
 (93K
===============================

tt1053960
200
The Midnight Sky
1h 58m
2020
5.7
 (93K
===============================

tt4560436
201
Mile 22
1h 34m
2018
6.1
 (92K
===============================

tt6513120
202
Fighting with My Family
1h 48m
2019
7.0
 (92K
===============================

tt3387520
203
Scary Stories to Tell in the Dark
1h 48m
2019
6.2
 (91K
===============================

tt2531344
204
Blockers
1h 42m
2018
6.2
 (91K
===============================

tt2990140
205
The Christmas Chronicles
1h 44m
2018
7.0
 (90K
===============================

tt1634106
206
Bloodshot
1h 49m
2020
5.7
 (90K
===============================

tt4575576
207
Christopher Robin
1h 44m
2018
7.2
 (89K
===============================

tt6921996
208
Johnny English Strikes Again
1h 29m
2018
6.2
 (89K
===============================

tt6977338
209
Good Boys
1h 30m
2019
6.7
 (88K
===============================

tt8359848
210
Climax
1h 37m
2018
6.9
 (88K
===============================

tt7638348
211
Boss Level
1h 40m
2020
6.8
 (87K
===============================

tt3861390
212
Dumbo
1h 52m
2019
6.2
 (87K
===============================

tt8368406
213
Vivarium
1h 37m
2019
5.9
 (87K
===============================

tt1061828
214
Mank
2h 11m
2020
6.8
 (87K
===============================

tt6679794
215
Outlaw King
2h 1m
2018
6.9
 (87K
===============================

tt6663582
216
The Spy Who Dumped Me
1h 57m
2018
6.1
 (86K
===============================

tt5613484
217
Mid90s
1h 25m
2018
7.4
 (86K
===============================

tt7014006
218
Eighth Grade
1h 33m
2018
7.3
 (86K
===============================

tt9866072
219
Holidate
1h 44m
2020
6.2
 (85K
===============================

tt4532826
220
Robin Hood
1h 56m
2018
5.4
 (85K
===============================

tt1005951
221
Unhinged
1h 30m
2020
6.0
 (85K
===============================

tt5033998
222
Charlie's Angels
1h 58m
2019
5.0
 (84K
===============================

tt7282468
223
Burning
2h 28m
2018
7.4
 (84K
===============================

tt7775622
224
Free Solo
1h 40m
2018
8.1
 (84K
===============================

tt5719748
225
Cold Pursuit
1h 59m
2019
6.2
 (83K
===============================

tt3513498
226
The Lego Movie 2: The Second Part
1h 47m
2019
6.5
 (83K
===============================

tt4916630
227
Just Mercy
2h 17m
2019
7.6
 (82K
===============================

tt1055423
228
Dara of Jasenovac
2h 10m
2020
8.0
 (82K
===============================

tt4477536
229
Fifty Shades Freed
1h 45m
2018
4.6
 (81K
===============================

tt9686708
230
The King of Staten Island
2h 16m
2020
7.1
 (81K
===============================

tt1137450
231
Death Wish
1h 47m
2018
6.3
 (81K
===============================

tt8368512
232
The Courier
1h 52m
2020
7.2
 (80K
===============================

tt1091938
233
Freaky
1h 42m
2020
6.3
 (80K
===============================

tt8688634
234
21 Bridges
1h 39m
2019
6.7

[{'movie_id': 'tt7286456',
  'rank': '1',
  'title': 'Joker',
  'runtime': '2h 2m',
  'year': '2019',
  'rating': '8.3',
  'votes': '\xa0(1.7M'},
 {'movie_id': 'tt4154796',
  'rank': '2',
  'title': 'Avengers: Endgame',
  'runtime': '3h 1m',
  'year': '2019',
  'rating': '8.4',
  'votes': '\xa0(1.4M'},
 {'movie_id': 'tt4154756',
  'rank': '3',
  'title': 'Avengers: Infinity War',
  'runtime': '2h 29m',
  'year': '2018',
  'rating': '8.4',
  'votes': '\xa0(1.3M'},
 {'movie_id': 'tt6751668',
  'rank': '4',
  'title': 'Parasite',
  'runtime': '2h 12m',
  'year': '2019',
  'rating': '8.5',
  'votes': '\xa0(1.1M'},
 {'movie_id': 'tt7131622',
  'rank': '5',
  'title': 'Once Upon a Time... in Hollywood',
  'runtime': '2h 41m',
  'year': '2019',
  'rating': '7.6',
  'votes': '\xa0(936K'},
 {'movie_id': 'tt1825683',
  'rank': '6',
  'title': 'Black Panther',
  'runtime': '2h 14m',
  'year': '2018',
  'rating': '7.3',
  'votes': '\xa0(893K'},
 {'movie_id': 'tt8946378',
  'rank': '7',
  'title': 'Knives Out',
  'runtime': '2h 10m',
  'year': '2019',
  'rating': '7.9',
  'votes': '\xa0(837K'},
 {'movie_id': 'tt4633694',
  'rank': '8',
  'title': 'Spider-Man: Into the Spider-Verse',
  'runtime': '1h 57m',
  'year': '2018',
  'rating': '8.4',
  'votes': '\xa0(758K'},
 {'movie_id': 'tt8579674',
  'rank': '9',
  'title': '1917',
  'runtime': '1h 59m',
  'year': '2019',
  'rating': '8.2',
  'votes': '\xa0(749K'},
 {'movie_id': 'tt5463162',
  'rank': '10',
  'title': 'Deadpool 2',
  'runtime': '1h 59m',
  'year': '2018',
  'rating': '7.6',
  'votes': '\xa0(729K'},
 {'movie_id': 'tt6966692',
  'rank': '11',
  'title': 'Green Book',
  'runtime': '2h 10m',
  'year': '2018',
  'rating': '8.2',
  'votes': '\xa0(661K'},
 {'movie_id': 'tt6723592',
  'rank': '12',
  'title': 'Tenet',
  'runtime': '2h 30m',
  'year': '2020',
  'rating': '7.3',
  'votes': '\xa0(648K'},
 {'movie_id': 'tt4154664',
  'rank': '13',
  'title': 'Captain Marvel',
  'runtime': '2h 3m',
  'year': '2019',
  'rating': '6.7',
  'votes': '\xa0(646K'},
 {'movie_id': 'tt6644200',
  'rank': '14',
  'title': 'A Quiet Place',
  'runtime': '1h 30m',
  'year': '2018',
  'rating': '7.5',
  'votes': '\xa0(644K'},
 {'movie_id': 'tt1727824',
  'rank': '15',
  'title': 'Bohemian Rhapsody',
  'runtime': '2h 14m',
  'year': '2018',
  'rating': '7.9',
  'votes': '\xa0(633K'},
 {'movie_id': 'tt6320628',
  'rank': '16',
  'title': 'Spider-Man: Far from Home',
  'runtime': '2h 9m',
  'year': '2019',
  'rating': '7.3',
  'votes': '\xa0(618K'},
 {'movie_id': 'tt1270797',
  'rank': '17',
  'title': 'Venom',
  'runtime': '1h 52m',
  'year': '2018',
  'rating': '6.6',
  'votes': '\xa0(593K'},
 {'movie_id': 'tt1950186',
  'rank': '18',
  'title': 'Ford v Ferrari',
  'runtime': '2h 32m',
  'year': '2019',
  'rating': '8.1',
  'votes': '\xa0(548K'},
 {'movie_id': 'tt1477834',
  'rank': '19',
  'title': 'Aquaman',
  'runtime': '2h 23m',
  'year': '2018',
  'rating': '6.8',
  'votes': '\xa0(546K'},
 {'movie_id': 'tt2527338',
  'rank': '20',
  'title': 'Star Wars: Episode IX - The Rise of Skywalker',
  'runtime': '2h 21m',
  'year': '2019',
  'rating': '6.4',
  'votes': '\xa0(530K'},
 {'movie_id': 'tt1677720',
  'rank': '21',
  'title': 'Ready Player One',
  'runtime': '2h 20m',
  'year': '2018',
  'rating': '7.4',
  'votes': '\xa0(530K'},
 {'movie_id': 'tt5095030',
  'rank': '22',
  'title': 'Ant-Man and the Wasp',
  'runtime': '1h 58m',
  'year': '2018',
  'rating': '7.0',
  'votes': '\xa0(484K'},
 {'movie_id': 'tt2584384',
  'rank': '23',
  'title': 'Jojo Rabbit',
  'runtime': '1h 48m',
  'year': '2019',
  'rating': '7.9',
  'votes': '\xa0(478K'},
 {'movie_id': 'tt6146586',
  'rank': '24',
  'title': 'John Wick: Chapter 3 - Parabellum',
  'runtime': '2h 10m',
  'year': '2019',
  'rating': '7.4',
  'votes': '\xa0(468K'},
 {'movie_id': 'tt8772262',
  'rank': '25',
  'title': 'Midsommar',
  'runtime': '2h 28m',
  'year': '2019',
  'rating': '7.1',
  'votes': '\xa0(468K'},
 {'movie_id': 'tt1302006',
  'rank': '26',
  'title': 'The Irishman',
  'runtime': '3h 29m',
  'year': '2019',
  'rating': '7.8',
  'votes': '\xa0(462K'},
 {'movie_id': 'tt8367814',
  'rank': '27',
  'title': 'The Gentlemen',
  'runtime': '1h 53m',
  'year': '2019',
  'rating': '7.8',
  'votes': '\xa0(445K'},
 {'movie_id': 'tt1517451',
  'rank': '28',
  'title': 'A Star Is Born',
  'runtime': '2h 16m',
  'year': '2018',
  'rating': '7.6',
  'votes': '\xa0(442K'},
 {'movie_id': 'tt7784604',
  'rank': '29',
  'title': 'Hereditary',
  'runtime': '2h 7m',
  'year': '2018',
  'rating': '7.3',
  'votes': '\xa0(440K'},
 {'movie_id': 'tt2948372',
  'rank': '30',
  'title': 'Soul',
  'runtime': '1h 40m',
  'year': '2020',
  'rating': '8.0',
  'votes': '\xa0(419K'},
 {'movie_id': 'tt2737304',
  'rank': '31',
  'title': 'Bird Box',
  'runtime': '2h 4m',
  'year': '2018',
  'rating': '6.6',
  'votes': '\xa0(414K'},
 {'movie_id': 'tt4912910',
  'rank': '32',
  'title': 'Mission: Impossible - Fallout',
  'runtime': '2h 27m',
  'year': '2018',
  'rating': '7.7',
  'votes': '\xa0(412K'},
 {'movie_id': 'tt0448115',
  'rank': '33',
  'title': 'Shazam!',
  'runtime': '2h 12m',
  'year': '2019',
  'rating': '7.0',
  'votes': '\xa0(408K'},
 {'movie_id': 'tt3778644',
  'rank': '34',
  'title': 'Solo: A Star Wars Story',
  'runtime': '2h 15m',
  'year': '2018',
  'rating': '6.9',
  'votes': '\xa0(402K'},
 {'movie_id': 'tt2798920',
  'rank': '35',
  'title': 'Annihilation',
  'runtime': '1h 55m',
  'year': '2018',
  'rating': '6.8',
  'votes': '\xa0(387K'},
 {'movie_id': 'tt6857112',
  'rank': '36',
  'title': 'Us',
  'runtime': '1h 56m',
  'year': '2019',
  'rating': '6.8',
  'votes': '\xa0(381K'},
 {'movie_id': 'tt4881806',
  'rank': '37',
  'title': 'Jurassic World: Fallen Kingdom',
  'runtime': '2h 8m',
  'year': '2018',
  'rating': '6.1',
  'votes': '\xa0(373K'},
 {'movie_id': 'tt7653254',
  'rank': '38',
  'title': 'Marriage Story',
  'runtime': '2h 17m',
  'year': '2019',
  'rating': '7.9',
  'votes': '\xa0(366K'},
 {'movie_id': 'tt3606756',
  'rank': '39',
  'title': 'Incredibles 2',
  'runtime': '1h 58m',
  'year': '2018',
  'rating': '7.5',
  'votes': '\xa0(361K'},
 {'movie_id': 'tt5727208',
  'rank': '40',
  'title': 'Uncut Gems',
  'runtime': '2h 15m',
  'year': '2019',
  'rating': '7.4',
  'votes': '\xa0(343K'},
 {'movie_id': 'tt7349950',
  'rank': '41',
  'title': 'It: Chapter Two',
  'runtime': '2h 49m',
  'year': '2019',
  'rating': '6.5',
  'votes': '\xa0(338K'},
 {'movie_id': 'tt9243946',
  'rank': '42',
  'title': 'El Camino',
  'runtime': '2h 2m',
  'year': '2019',
  'rating': '7.3',
  'votes': '\xa0(328K'},
 {'movie_id': 'tt4123430',
  'rank': '43',
  'title': 'Fantastic Beasts: The Crimes of Grindelwald',
  'runtime': '2h 14m',
  'year': '2018',
  'rating': '6.5',
  'votes': '\xa0(326K'},
 {'movie_id': 'tt0437086',
  'rank': '44',
  'title': 'Alita: Battle Angel',
  'runtime': '2h 2m',
  'year': '2019',
  'rating': '7.3',
  'votes': '\xa0(318K'},
 {'movie_id': 'tt8228288',
  'rank': '45',
  'title': 'The Platform',
  'runtime': '1h 34m',
  'year': '2019',
  'rating': '7.0',
  'votes': '\xa0(316K'},
 {'movie_id': 'tt8332922',
  'rank': '46',
  'title': 'A Quiet Place Part II',
  'runtime': '1h 37m',
  'year': '2020',
  'rating': '7.2',
  'votes': '\xa0(314K'},
 {'movie_id': 'tt7975244',
  'rank': '47',
  'title': 'Jumanji: The Next Level',
  'runtime': '2h 3m',
  'year': '2019',
  'rating': '6.6',
  'votes': '\xa0(311K'},
 {'movie_id': 'tt6139732',
  'rank': '48',
  'title': 'Aladdin',
  'runtime': '2h 8m',
  'year': '2019',
  'rating': '6.9',
  'votes': '\xa0(309K'},
 {'movie_id': 'tt7349662',
  'rank': '49',
  'title': 'BlacKkKlansman',
  'runtime': '2h 15m',
  'year': '2018',
  'rating': '7.5',
  'votes': '\xa0(308K'},
 {'movie_id': 'tt7126948',
  'rank': '50',
  'title': 'Wonder Woman 1984',
  'runtime': '2h 31m',
  'year': '2020',
  'rating': '5.3',
  'votes': '\xa0(307K'},
 {'movie_id': 'tt1979376',
  'rank': '51',
  'title': 'Toy Story 4',
  'runtime': '1h 40m',
  'year': '2019',
  'rating': '7.6',
  'votes': '\xa0(305K'},
 {'movie_id': 'tt6823368',
  'rank': '52',
  'title': 'Glass',
  'runtime': '2h 9m',
  'year': '2019',
  'rating': '6.6',
  'votes': '\xa0(299K'},
 {'movie_id': 'tt7984734',
  'rank': '53',
  'title': 'The Lighthouse',
  'runtime': '1h 49m',
  'year': '2019',
  'rating': '7.4',
  'votes': '\xa0(293K'},
 {'movie_id': 'tt6105098',
  'rank': '54',
  'title': 'The Lion King',
  'runtime': '1h 58m',
  'year': '2019',
  'rating': '6.8',
  'votes': '\xa0(287K'},
 {'movie_id': 'tt8936646',
  'rank': '55',
  'title': 'Extraction',
  'runtime': '1h 56m',
  'year': '2020',
  'rating': '6.8',
  'votes': '\xa0(284K'},
 {'movie_id': 'tt7713068',
  'rank': '56',
  'title': 'Birds of Prey and the Fantabulous Emancipation of One Harley Quinn',
  'runtime': '1h 49m',
  'year': '2020',
  'rating': '6.1',
  'votes': '\xa0(279K'},
 {'movie_id': 'tt1051906',
  'rank': '57',
  'title': 'The Invisible Man',
  'runtime': '2h 4m',
  'year': '2020',
  'rating': '7.1',
  'votes': '\xa0(278K'},
 {'movie_id': 'tt3281548',
  'rank': '58',
  'title': 'Little Women',
  'runtime': '2h 15m',
  'year': '2019',
  'rating': '7.8',
  'votes': '\xa0(276K'},
 {'movie_id': 'tt2935510',
  'rank': '59',
  'title': 'Ad Astra',
  'runtime': '2h 3m',
  'year': '2019',
  'rating': '6.5',
  'votes': '\xa0(275K'},
 {'movie_id': 'tt2704998',
  'rank': '60',
  'title': 'Game Night',
  'runtime': '1h 40m',
  'year': '2018',
  'rating': '6.9',
  'votes': '\xa0(271K'},
 {'movie_id': 'tt5164214',
  'rank': '61',
  'title': "Ocean's Eight",
  'runtime': '1h 50m',
  'year': '2018',
  'rating': '6.3',
  'votes': '\xa0(257K'},
 {'movie_id': 'tt5083738',
  'rank': '62',
  'title': 'The Favourite',
  'runtime': '1h 59m',
  'year': '2018',
  'rating': '7.5',
  'votes': '\xa0(253K'},
 {'movie_id': 'tt6806448',
  'rank': '63',
  'title': 'Fast & Furious Presents: Hobbs & Shaw',
  'runtime': '2h 17m',
  'year': '2019',
  'rating': '6.4',
  'votes': '\xa0(252K'},
 {'movie_id': 'tt7846844',
  'rank': '64',
  'title': 'Enola Holmes',
  'runtime': '2h 3m',
  'year': '2020',
  'rating': '6.6',
  'votes': '\xa0(239K'},
 {'movie_id': 'tt5606664',
  'rank': '65',
  'title': 'Doctor Sleep',
  'runtime': '2h 32m',
  'year': '2019',
  'rating': '7.3',
  'votes': '\xa0(238K'},
 {'movie_id': 'tt1365519',
  'rank': '66',
  'title': 'Tomb Raider',
  'runtime': '1h 59m',
  'year': '2018',
  'rating': '6.3',
  'votes': '\xa0(238K'},
 {'movie_id': 'tt9620292',
  'rank': '67',
  'title': 'Promising Young Woman',
  'runtime': '1h 53m',
  'year': '2020',
  'rating': '7.5',
  'votes': '\xa0(231K'},
 {'movie_id': 'tt6499752',
  'rank': '68',
  'title': 'Upgrade',
  'runtime': '1h 40m',
  'year': '2018',
  'rating': '7.5',
  'votes': '\xa0(229K'},
 {'movie_id': 'tt7798634',
  'rank': '69',
  'title': 'Ready or Not',
  'runtime': '1h 35m',
  'year': '2019',
  'rating': '6.8',
  'votes': '\xa0(225K'},
 {'movie_id': 'tt3741700',
  'rank': '70',
  'title': 'Godzilla: King of the Monsters',
  'runtime': '2h 12m',
  'year': '2019',
  'rating': '6.0',
  'votes': '\xa0(224K'},
 {'movie_id': 'tt4779682',
  'rank': '71',
  'title': 'The Meg',
  'runtime': '1h 53m',
  'year': '2018',
  'rating': '5.7',
  'votes': '\xa0(224K'},
 {'movie_id': 'tt6565702',
  'rank': '72',
  'title': 'X-Men: Dark Phoenix',
  'runtime': '1h 53m',
  'year': '2019',
  'rating': '5.7',
  'votes': '\xa0(223K'},
 {'movie_id': 'tt3766354',
  'rank': '73',
  'title': 'The Equalizer 2',
  'runtime': '2h 1m',
  'year': '2018',
  'rating': '6.7',
  'votes': '\xa0(223K'},
 {'movie_id': 'tt4729430',
  'rank': '74',
  'title': 'Klaus',
  'runtime': '1h 36m',
  'year': '2019',
  'rating': '8.2',
  'votes': '\xa0(222K'},
 {'movie_id': 'tt1027238',
  'rank': '75',
  'title': 'The Father',
  'runtime': '1h 37m',
  'year': '2020',
  'rating': '8.2',
  'votes': '\xa0(221K'},
 {'movie_id': 'tt1560220',
  'rank': '76',
  'title': 'Zombieland: Double Tap',
  'runtime': '1h 39m',
  'year': '2019',
  'rating': '6.7',
  'votes': '\xa0(220K'},
 {'movie_id': 'tt1028856',
  'rank': '77',
  'title': 'Another Round',
  'runtime': '1h 57m',
  'year': '2020',
  'rating': '7.7',
  'votes': '\xa0(220K'},
 {'movie_id': 'tt2873282',
  'rank': '78',
  'title': 'Red Sparrow',
  'runtime': '2h 20m',
  'year': '2018',
  'rating': '6.6',
  'votes': '\xa0(215K'},
 {'movie_id': 'tt1213641',
  'rank': '79',
  'title': 'First Man',
  'runtime': '2h 21m',
  'year': '2018',
  'rating': '7.3',
  'votes': '\xa0(213K'},
 {'movie_id': 'tt4520988',
  'rank': '80',
  'title': 'Frozen II',
  'runtime': '1h 43m',
  'year': '2019',
  'rating': '6.8',
  'votes': '\xa0(213K'},
 {'movie_id': 'tt6450804',
  'rank': '81',
  'title': 'Terminator: Dark Fate',
  'runtime': '2h 8m',
  'year': '2019',
  'rating': '6.2',
  'votes': '\xa0(208K'},
 {'movie_id': 'tt8106534',
  'rank': '82',
  'title': '6 Underground',
  'runtime': '2h 8m',
  'year': '2019',
  'rating': '6.1',
  'votes': '\xa0(208K'},
 {'movie_id': 'tt9484998',
  'rank': '83',
  'title': 'Palm Springs',
  'runtime': '1h 30m',
  'year': '2020',
  'rating': '7.4',
  'votes': '\xa0(207K'},
 {'movie_id': 'tt7556122',
  'rank': '84',
  'title': 'The Old Guard',
  'runtime': '2h 5m',
  'year': '2020',
  'rating': '6.7',
  'votes': '\xa0(207K'},
 {'movie_id': 'tt2066051',
  'rank': '85',
  'title': 'Rocketman',
  'runtime': '2h 1m',
  'year': '2019',
  'rating': '7.3',
  'votes': '\xa0(206K'},
 {'movie_id': 'tt5104604',
  'rank': '86',
  'title': 'Isle of Dogs',
  'runtime': '1h 41m',
  'year': '2018',
  'rating': '7.8',
  'votes': '\xa0(206K'},
 {'movie_id': 'tt3104988',
  'rank': '87',
  'title': 'Crazy Rich Asians',
  'runtime': '2h',
  'year': '2018',
  'rating': '6.9',
  'votes': '\xa0(205K'},
 {'movie_id': 'tt4701182',
  'rank': '88',
  'title': 'Bumblebee',
  'runtime': '1h 54m',
  'year': '2018',
  'rating': '6.7',
  'votes': '\xa0(204K'},
 {'movie_id': 'tt1070874',
  'rank': '89',
  'title': 'The Trial of the Chicago 7',
  'runtime': '2h 9m',
  'year': '2020',
  'rating': '7.7',
  'votes': '\xa0(203K'},
 {'movie_id': 'tt5848272',
  'rank': '90',
  'title': 'Ralph Breaks the Internet',
  'runtime': '1h 52m',
  'year': '2018',
  'rating': '7.0',
  'votes': '\xa0(200K'},
 {'movie_id': 'tt2231461',
  'rank': '91',
  'title': 'Rampage',
  'runtime': '1h 47m',
  'year': '2018',
  'rating': '6.1',
  'votes': '\xa0(198K'},
 {'movie_id': 'tt9770150',
  'rank': '92',
  'title': 'Nomadland',
  'runtime': '1h 47m',
  'year': '2020',
  'rating': '7.3',
  'votes': '\xa0(197K'},
 {'movie_id': 'tt1502397',
  'rank': '93',
  'title': 'Bad Boys for Life',
  'runtime': '2h 4m',
  'year': '2020',
  'rating': '6.5',
  'votes': '\xa0(194K'},
 {'movie_id': 'tt5884052',
  'rank': '94',
  'title': 'Pokémon: Detective Pikachu',
  'runtime': '1h 44m',
  'year': '2019',
  'rating': '6.5',
  'votes': '\xa0(194K'},
 {'movie_id': 'tt5814060',
  'rank': '95',
  'title': 'The Nun',
  'runtime': '1h 36m',
  'year': '2018',
  'rating': '5.4',
  'votes': '\xa0(191K'},
 {'movie_id': 'tt7668870',
  'rank': '96',
  'title': 'Searching',
  'runtime': '1h 42m',
  'year': '2018',
  'rating': '7.6',
  'votes': '\xa0(190K'},
 {'movie_id': 'tt7040874',
  'rank': '97',
  'title': 'A Simple Favor',
  'runtime': '1h 57m',
  'year': '2018',
  'rating': '6.7',
  'votes': '\xa0(188K'},
 {'movie_id': 'tt3794354',
  'rank': '98',
  'title': 'Sonic the Hedgehog',
  'runtime': '1h 39m',
  'year': '2020',
  'rating': '6.5',
  'votes': '\xa0(187K'},
 {'movie_id': 'tt1618434',
  'rank': '99',
  'title': 'Murder Mystery',
  'runtime': '1h 37m',
  'year': '2019',
  'rating': '6.1',
  'votes': '\xa0(185K'},
 {'movie_id': 'tt5052474',
  'rank': '100',
  'title': 'Sicario: Day of the Soldado',
  'runtime': '2h 2m',
  'year': '2018',
  'rating': '7.1',
  'votes': '\xa0(185K'},
 {'movie_id': 'tt4500922',
  'rank': '101',
  'title': 'Maze Runner: The Death Cure',
  'runtime': '2h 23m',
  'year': '2018',
  'rating': '6.3',
  'votes': '\xa0(184K'},
 {'movie_id': 'tt1502407',
  'rank': '102',
  'title': 'Halloween',
  'runtime': '1h 46m',
  'year': '2018',
  'rating': '6.5',
  'votes': '\xa0(184K'},
 {'movie_id': 'tt7146812',
  'rank': '103',
  'title': 'Onward',
  'runtime': '1h 42m',
  'year': '2020',
  'rating': '7.4',
  'votes': '\xa0(183K'},
 {'movie_id': 'tt8079248',
  'rank': '104',
  'title': 'Yesterday',
  'runtime': '1h 56m',
  'year': '2019',
  'rating': '6.8',
  'votes': '\xa0(181K'},
 {'movie_id': 'tt6412452',
  'rank': '105',
  'title': 'The Ballad of Buster Scruggs',
  'runtime': '2h 13m',
  'year': '2018',
  'rating': '7.2',
  'votes': '\xa0(180K'},
 {'movie_id': 'tt6155172',
  'rank': '106',
  'title': 'Roma',
  'runtime': '2h 15m',
  'year': '2018',
  'rating': '7.6',
  'votes': '\xa0(176K'},
 {'movie_id': 'tt6628394',
  'rank': '107',
  'title': 'Bad Times at the El Royale',
  'runtime': '2h 21m',
  'year': '2018',
  'rating': '7.1',
  'votes': '\xa0(176K'},
 {'movie_id': 'tt2386490',
  'rank': '108',
  'title': 'How to Train Your Dragon: The Hidden World',
  'runtime': '1h 44m',
  'year': '2019',
  'rating': '7.4',
  'votes': '\xa0(173K'},
 {'movie_id': 'tt6266538',
  'rank': '109',
  'title': 'Vice',
  'runtime': '2h 12m',
  'year': '2018',
  'rating': '7.2',
  'votes': '\xa0(172K'},
 {'movie_id': 'tt7984766',
  'rank': '110',
  'title': 'The King',
  'runtime': '2h 20m',
  'year': '2019',
  'rating': '7.3',
  'votes': '\xa0(171K'},
 {'movie_id': 'tt6343314',
  'rank': '111',
  'title': 'Creed II',
  'runtime': '2h 10m',
  'year': '2018',
  'rating': '7.1',
  'votes': '\xa0(167K'},
 {'movie_id': 'tt4566758',
  'rank': '112',
  'title': 'Mulan',
  'runtime': '1h 55m',
  'year': '2020',
  'rating': '5.8',
  'votes': '\xa0(166K'},
 {'movie_id': 'tt7959026',
  'rank': '113',
  'title': 'The Mule',
  'runtime': '1h 56m',
  'year': '2018',
  'rating': '7.0',
  'votes': '\xa0(166K'},
 {'movie_id': 'tt7395114',
  'rank': '114',
  'title': 'The Devil All the Time',
  'runtime': '2h 18m',
  'year': '2020',
  'rating': '7.1',
  'votes': '\xa0(165K'},
 {'movie_id': 'tt5363618',
  'rank': '115',
  'title': 'Sound of Metal',
  'runtime': '2h',
  'year': '2019',
  'rating': '7.7',
  'votes': '\xa0(164K'},
 {'movie_id': 'tt1314396',
  'rank': '116',
  'title': 'Borat Subsequent Moviefilm',
  'runtime': '1h 35m',
  'year': '2020',
  'rating': '6.6',
  'votes': '\xa0(162K'},
 {'movie_id': 'tt2854926',
  'rank': '117',
  'title': 'Tag',
  'runtime': '1h 40m',
  'year': '2018',
  'rating': '6.5',
  'votes': '\xa0(159K'},
 {'movie_id': 'tt3829266',
  'rank': '118',
  'title': 'The Predator',
  'runtime': '1h 47m',
  'year': '2018',
  'rating': '5.3',
  'votes': '\xa0(158K'},
 {'movie_id': 'tt1488606',
  'rank': '119',
  'title': 'Triple Frontier',
  'runtime': '2h 5m',
  'year': '2019',
  'rating': '6.5',
  'votes': '\xa0(158K'},
 {'movie_id': 'tt2283336',
  'rank': '120',
  'title': 'Men in Black: International',
  'runtime': '1h 54m',
  'year': '2019',
  'rating': '5.6',
  'votes': '\xa0(158K'},
 {'movie_id': 'tt2222042',
  'rank': '121',
  'title': 'Love and Monsters',
  'runtime': '1h 49m',
  'year': '2020',
  'rating': '6.9',
  'votes': '\xa0(156K'},
 {'movie_id': 'tt9893250',
  'rank': '122',
  'title': 'I Care a Lot',
  'runtime': '1h 58m',
  'year': '2020',
  'rating': '6.4',
  'votes': '\xa0(156K'},
 {'movie_id': 'tt5886046',
  'rank': '123',
  'title': 'Escape Room',
  'runtime': '1h 39m',
  'year': '2019',
  'rating': '6.4',
  'votes': '\xa0(156K'},
 {'movie_id': 'tt7737786',
  'rank': '124',
  'title': 'Greenland',
  'runtime': '1h 59m',
  'year': '2020',
  'rating': '6.4',
  'votes': '\xa0(151K'},
 {'movie_id': 'tt1571234',
  'rank': '125',
  'title': 'Mortal Engines',
  'runtime': '2h 8m',
  'year': '2018',
  'rating': '6.1',
  'votes': '\xa0(151K'},
 {'movie_id': 'tt1259528',
  'rank': '126',
  'title': 'Den of Thieves',
  'runtime': '2h 20m',
  'year': '2018',
  'rating': '7.0',
  'votes': '\xa0(150K'},
 {'movie_id': 'tt8244784',
  'rank': '127',
  'title': 'The Hunt',

In [6]:
# to convert the movies list of dics to dataframe
df_movies = pd.DataFrame(Movies_list)
df_movies

,movie_id,rank,title,runtime,year,rating,votes
0,tt7286456,1,Joker,2h 2m,2019,8.3,(1.7M
1,tt4154796,2,Avengers: Endgame,3h 1m,2019,8.4,(1.4M
2,tt4154756,3,Avengers: Infinity War,2h 29m,2018,8.4,(1.3M
3,tt6751668,4,Parasite,2h 12m,2019,8.5,(1.1M
4,tt7131622,5,Once Upon a Time... in Hollywood,2h 41m,2019,7.6,(936K
...,...,...,...,...,...,...,...
495,tt8385474,496,A Dog's Journey,1h 49m,2019,7.4,(32K
496,tt6587640,497,Trolls World Tour,1h 31m,2020,6.1,(32K
497,tt2126357,498,Second Act,1h 43m,2018,5.8,(32K
498,tt3612126,499,The Grudge,1h 34m,2019,4.4,(32K
499,tt7218518,500,Pad Man,2h 20m,2018,7.8,(32K

***
#  To export the colleted movies to IMDb_TopVoted.csv file.

In [7]:
df_movies.to_csv('IMDb_TopVoted.csv', index = False)

# Importing the given dataset "Movies.csv" to Pandas DataFrame called df1

In [8]:
# Importing the csv file to df1 and print the df1.

df1 = pd.read_csv('Movies.csv', encoding="ISO-8859-1")
print("Movies.csv loaded:")
print(f"Shape: {df1.shape}")
df1.head()

Movies.csv loaded:
Shape: (500, 5)

,movie_id,originalTitle,description,ratingCategory,genres
0,tt7286456,Joker,"During the 1980s, a failed stand-up comedian i...",R,"Crime,Drama,Thriller"
1,tt4154796,Avengers: Endgame,After the devastating events of Avengers: Infi...,PG-13,"Action,Adventure,Drama"
2,tt4154756,Avengers: Infinity War,The Avengers and their allies must be willing ...,PG-13,"Action,Adventure,Sci-Fi"
3,tt6751668,Parasite,Greed and class discrimination threaten the ne...,R,"Drama,Thriller"
4,tt1825683,Black Panther,"T'Challa, heir to the hidden but advanced king...",PG-13,"Action,Adventure,Sci-Fi"

# Import the scraped data from the IMDb_TopVoted.csv file to Pandas DataFrame called df2

In [9]:
# You need to import the collected dataset "IMDb_TopVoted.csv" and print the df2.
# To handel Latin characters that may contained in the csv file
# with no issue, use  encoding= "ISO-8859-1" with the pd.read_csv()
# Example: df1 = pd.read_csv('thefilename.csv', encoding= "ISO-8859-1") 
# Using encoding= "ISO-8859-1" will avoid Unicode-Decode-Errors.

df2 = pd.read_csv('IMDb_TopVoted.csv', encoding="ISO-8859-1")
print("IMDb_TopVoted.csv loaded:")
print(f"Shape: {df2.shape}")
df2.head()

IMDb_TopVoted.csv loaded:
Shape: (500, 7)

,movie_id,rank,title,runtime,year,rating,votes
0,tt7286456,1,Joker,2h 2m,2019,8.3,Â (1.7M
1,tt4154796,2,Avengers: Endgame,3h 1m,2019,8.4,Â (1.4M
2,tt4154756,3,Avengers: Infinity War,2h 29m,2018,8.4,Â (1.3M
3,tt6751668,4,Parasite,2h 12m,2019,8.5,Â (1.1M
4,tt7131622,5,Once Upon a Time... in Hollywood,2h 41m,2019,7.6,Â (936K

# Data cleansing and transformation for df2.

In [ ]:
df2.info()

In [10]:
# Cleaning and tranforming df2
 # rank, year, and votes should have a numeric integer data type.
 # runtime column should be renamed to runtimeMinutes and the value should be in minutes, 
 # for example: 2h 2m should be 122
    
# Fix votes with a better function
def clean_votes(vote_str):
    if pd.isna(vote_str) or vote_str == "":
        return 0
    try:
        vote_str = str(vote_str).strip()
        
        # Remove all whitespace and special characters, keep only numbers, M, K, and decimal
        import re
        # Find pattern like "1.7M" or "936K"
        match = re.search(r'(\d+\.?\d*)[MK]', vote_str)
        
        if match:
            number = float(match.group(1))
            if 'M' in vote_str:
                return int(number * 1000000)
            elif 'K' in vote_str:
                return int(number * 1000)
        
        # If no M or K, try to extract plain number
        numbers = re.findall(r'\d+', vote_str)
        if numbers:
            return int(''.join(numbers))
        
        return 0
    except Exception as e:
        print(f"Error with: {vote_str}")
        return 0

df2['votes'] = df2['votes'].apply(clean_votes)

# Convert runtime to minutes
def convert_runtime_to_minutes(runtime):
    if pd.isna(runtime) or runtime == "":
        return None
    try:
        hours = 0
        minutes = 0
        runtime = str(runtime).strip()
        
        if 'h' in runtime:
            parts = runtime.split('h')
            hours = int(parts[0].strip())
            if len(parts) > 1 and 'm' in parts[1]:
                minutes = int(parts[1].replace('m', '').strip())
        elif 'm' in runtime:
            minutes = int(runtime.replace('m', '').strip())
        
        return hours * 60 + minutes
    except:
        return None

df2['runtimeMinutes'] = df2['runtime'].apply(convert_runtime_to_minutes)
df2 = df2.drop('runtime', axis=1)

print("After cleaning:")
df2.info()
print("\n")
df2.head(10)

After cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_id        500 non-null    object
 1   rank            500 non-null    int64
 2   title           500 non-null    object
 3   year            500 non-null    int64
 4   rating          500 non-null    float64
 5   votes           500 non-null    int64
 6   runtimeMinutes  500 non-null    int64
dtypes: float64(1), int64(4), object(2)
memory usage: 27.5+ KB

,movie_id,rank,title,year,rating,votes,runtimeMinutes
0,tt7286456,1,Joker,2019,8.3,1700000,122
1,tt4154796,2,Avengers: Endgame,2019,8.4,1400000,181
2,tt4154756,3,Avengers: Infinity War,2018,8.4,1300000,149
3,tt6751668,4,Parasite,2019,8.5,1100000,132
4,tt7131622,5,Once Upon a Time... in Hollywood,2019,7.6,936000,161
5,tt1825683,6,Black Panther,2018,7.3,893000,134
6,tt8946378,7,Knives Out,2019,7.9,837000,130
7,tt4633694,8,Spider-Man: Into the Spider-Verse,2018,8.4,758000,117
8,tt8579674,9,1917,2019,8.2,749000,119
9,tt5463162,10,Deadpool 2,2018,7.6,729000,119

# 	Enrich the given dataset (df1) by merging it to the scraped data (df2).

In [11]:
# Merege the two dataframes to one dataframe called df.
df = pd.merge(df1, df2, on='movie_id', how='inner')

print("="*60)
print("MERGE RESULTS")
print("="*60)
print(f"\ndf1 shape: {df1.shape}")
print(f"df2 shape: {df2.shape}")
print(f"Merged df shape: {df.shape}")
print(f"\nAll movies successfully matched: {df.shape[0] == df1.shape[0]}")

print(f"\nColumns in merged dataset:")
print(list(df.columns))

print("\n" + "="*60)
print("MERGED DATA INFO:")
print("="*60)
df.info()

print("\n" + "="*60)
print("SAMPLE OF MERGED DATA:")
print("="*60)
df.head(10)

============================================================
MERGE RESULTS
============================================================

df1 shape: (500, 5)
df2 shape: (500, 7)
Merged df shape: (492, 11)

All movies successfully matched: False

Columns in merged dataset:
['movie_id', 'originalTitle', 'description', 'ratingCategory', 'genres', 'rank', 'title', 'year', 'rating', 'votes', 'runtimeMinutes']

============================================================
MERGED DATA INFO:
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_id        492 non-null    object
 1   originalTitle   492 non-null    object
 2   description     492 non-null    object
 3   ratingCategory  489 non-null    object
 4   genres          492 non-null    object
 5   rank            492 non-null    int64
 6   title           492 non-null    object
 7   year            492 non-null    int64
 8   rating          492 non-null    float64
 9   votes           492 non-null    int64
 10  runtimeMinutes  492 non-null    int64
dtypes: float64(1), int64(4), object(6)
memory usage: 42.4+ KB

============================================================
SAMPLE OF MERGED DATA:
============================================================

,movie_id,originalTitle,description,ratingCategory,genres,rank,title,year,rating,votes,runtimeMinutes
0,tt7286456,Joker,"During the 1980s, a failed stand-up comedian i...",R,"Crime,Drama,Thriller",1,Joker,2019,8.3,1700000,122
1,tt4154796,Avengers: Endgame,After the devastating events of Avengers: Infi...,PG-13,"Action,Adventure,Drama",2,Avengers: Endgame,2019,8.4,1400000,181
2,tt4154756,Avengers: Infinity War,The Avengers and their allies must be willing ...,PG-13,"Action,Adventure,Sci-Fi",3,Avengers: Infinity War,2018,8.4,1300000,149
3,tt6751668,Parasite,Greed and class discrimination threaten the ne...,R,"Drama,Thriller",4,Parasite,2019,8.5,1100000,132
4,tt1825683,Black Panther,"T'Challa, heir to the hidden but advanced king...",PG-13,"Action,Adventure,Sci-Fi",6,Black Panther,2018,7.3,893000,134
5,tt7131622,Once Upon a Time in Hollywood,A faded television actor and his stunt double ...,R,"Comedy,Drama",5,Once Upon a Time... in Hollywood,2019,7.6,936000,161
6,tt8946378,Knives Out,A detective investigates the death of the patr...,PG-13,"Comedy,Crime,Drama",7,Knives Out,2019,7.9,837000,130
7,tt8579674,1917,"April 6th, 1917. As an infantry battalion asse...",R,"Action,Drama,War",9,1917,2019,8.2,749000,119
8,tt4633694,Spider-Man: Into the Spider-Verse,Teen Miles Morales becomes the Spider-Man of h...,PG,"Action,Adventure,Animation",8,Spider-Man: Into the Spider-Verse,2018,8.4,758000,117
9,tt5463162,Deadpool 2,Foul-mouthed mutant mercenary Wade Wilson (a.k...,R,"Action,Adventure,Comedy",10,Deadpool 2,2018,7.6,729000,119

# Rearrange the dataset fields to be listed in the following order: 
movie_id , rank , title ,  originalTitle ,  description ,
          year ,  votes , rating ,  runtimeMinutes ,  ratingCategory ,  genres

In [12]:
# Rearrange the dataset fields.
df = df[['movie_id', 'rank', 'title', 'originalTitle', 'description', 
         'year', 'votes', 'rating', 'runtimeMinutes', 'ratingCategory', 'genres']]

print("Columns after rearranging:")
print(list(df.columns))
print("\nDataset shape:", df.shape)
print("\nSample data with new column order:")
df.head(10)

Columns after rearranging:
['movie_id', 'rank', 'title', 'originalTitle', 'description', 'year', 'votes', 'rating', 'runtimeMinutes', 'ratingCategory', 'genres']

Dataset shape: (492, 11)

Sample data with new column order:

,movie_id,rank,title,originalTitle,description,year,votes,rating,runtimeMinutes,ratingCategory,genres
0,tt7286456,1,Joker,Joker,"During the 1980s, a failed stand-up comedian i...",2019,1700000,8.3,122,R,"Crime,Drama,Thriller"
1,tt4154796,2,Avengers: Endgame,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,1400000,8.4,181,PG-13,"Action,Adventure,Drama"
2,tt4154756,3,Avengers: Infinity War,Avengers: Infinity War,The Avengers and their allies must be willing ...,2018,1300000,8.4,149,PG-13,"Action,Adventure,Sci-Fi"
3,tt6751668,4,Parasite,Parasite,Greed and class discrimination threaten the ne...,2019,1100000,8.5,132,R,"Drama,Thriller"
4,tt1825683,6,Black Panther,Black Panther,"T'Challa, heir to the hidden but advanced king...",2018,893000,7.3,134,PG-13,"Action,Adventure,Sci-Fi"
5,tt7131622,5,Once Upon a Time... in Hollywood,Once Upon a Time in Hollywood,A faded television actor and his stunt double ...,2019,936000,7.6,161,R,"Comedy,Drama"
6,tt8946378,7,Knives Out,Knives Out,A detective investigates the death of the patr...,2019,837000,7.9,130,PG-13,"Comedy,Crime,Drama"
7,tt8579674,9,1917,1917,"April 6th, 1917. As an infantry battalion asse...",2019,749000,8.2,119,R,"Action,Drama,War"
8,tt4633694,8,Spider-Man: Into the Spider-Verse,Spider-Man: Into the Spider-Verse,Teen Miles Morales becomes the Spider-Man of h...,2018,758000,8.4,117,PG,"Action,Adventure,Animation"
9,tt5463162,10,Deadpool 2,Deadpool 2,Foul-mouthed mutant mercenary Wade Wilson (a.k...,2018,729000,7.6,119,R,"Action,Adventure,Comedy"

# Export the enriched dataset to a CSV file:

In [13]:
# Use the following naming convention: 
#  Project_3_PartA_Lastname.csv
filename = 'Project_3_PartA_Group6.csv'  

df.to_csv(filename, index=False, encoding='utf-8')

print(f"✅ Enriched dataset exported successfully!")
print(f"Filename: {filename}")
print(f"Total records: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print(f"\nFinal dataset summary:")
df.info()

✅ Enriched dataset exported successfully!
Filename: Project_3_PartA_Group6.csv
Total records: 492
Total columns: 11

Final dataset summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_id        492 non-null    object
 1   rank            492 non-null    int64
 2   title           492 non-null    object
 3   originalTitle   492 non-null    object
 4   description     492 non-null    object
 5   year            492 non-null    int64
 6   votes           492 non-null    int64
 7   rating          492 non-null    float64
 8   runtimeMinutes  492 non-null    int64
 9   ratingCategory  489 non-null    object
 10  genres          492 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 42.4+ KB